<?php

namespace ABCoursework;

use DateTime;
use Psr\Log\LoggerInterface;

/**
 * MessageModel: Class for performing functions for M2M messages using a database or SOAP connection.
 * @package ABCoursework
 * @author Team AB (Jared)
 */
class MessageModel
{
    /**
     * @var LoggerInterface Logger used to log user actions.
     */
    private LoggerInterface $logger;

    /**
     * @var SoapWrapper Wrapper used to communicate with the SOAP server.
     */
    private SoapWrapper $soapWrapper;

    /**
     * @var DatabaseWrapper Wrapper for database connections, for execution and fetching.
     */
    private DatabaseWrapper $dbWrapper;

    /**
     * @var SqlQueries SqlQueries contain Doctrine QueryBuilder queries for use with DatabaseWrapper.
     */
    private SqlQueries $queries;

    /**
     * @var array Array containing SOAP server login details, with username and password key/value pairs.
     */
    private array $soapLogin;

    /**
     * @var array Errors generated by methods in this model.
     */
    private array $errors;

    /**
     * Creates a new UserModel instance with the specified Logger, DatabaseWrapper and SqlQueries.
     * @param LoggerInterface $logger Logger used to log user actions such as logging in, registering etc.
     * @param SoapWrapper $soapWrapper Wrapper used to communicate with the SOAP server.
     * @param DatabaseWrapper $dbWrapper Wrapper for database connections, for execution and fetching.
     * @param SqlQueries $queries SqlQueries contain Doctrine QueryBuilder queries for use with DatabaseWrapper.
     * @param array Array containing SOAP server login details, with username and password key/value pairs.
     */
    public function __construct(
        LoggerInterface $logger,
        SoapWrapper $soapWrapper,
        DatabaseWrapper $dbWrapper,
        SqlQueries $queries,
        array $soapLogin
    )
    {
        $this->logger = $logger;
        $this->soapWrapper = $soapWrapper;
        $this->dbWrapper = $dbWrapper;
        $this->queries = $queries;
        $this->errors = [];
        $this->soapLogin = $soapLogin;
    }

    /**
     * Returns all errors from this model.
     * @return array Errors generated by methods in this model.
     */
    public function getErrors(): array
    {
        return $this->errors;
    }

    /**
     * Send a message using the SOAP service connection made by SoapWrapper.
     * @param string $username Application username used for logging.
     * @param string $destination Destination phone number, without the +.
     * @param string $message Message to be sent.
     * @return bool Whether the message sent successfully.
     */
    public function sendMessage(string $username, string $destination, string $message): bool
    {
        $result = false;

        $this->logger->info('SOAP Message Send Request', [
            'username' => $username,
            'destination' => $destination,
            'message' => $message
        ]);

        $sendMsg = $this->soapWrapper->performSoapFunction($username, 'sendMessage', [
            'username' => $this->soapLogin['username'],
            'password' => $this->soapLogin['password'],
            'deviceMSISDN' => '+' . $destination,
            'message' => $message,
            'deliveryReport' => 0,
            'mtBearer' => 'SMS'
        ]);

        if ($sendMsg !== null) {
            $result = true;
        } else {
            $this->errors['soap'] = 'A SOAP error has occurred, please try again later!';
        }

        return $result;
    }

    /**
     * Gets a number of messages from the database and returns them as an array.
     * @param string $username User's username for logging activity.
     * @param int $numberOfMessages Maximum number of messages to retrieve from database.
     * @return array Array of messages from the database.
     */
    public function getMessages(string $username, int $numberOfMessages): array
    {
        $result = [];

        $this->logger->info('Database Message Request', [
            'username' => $username,
            'numberOfMessages' => $numberOfMessages
        ]);

        $query = $this->queries->getMessages($numberOfMessages);
        if ($query) {
            $queryResult = $this->dbWrapper->executeAndFetchAll($query);
            if ($queryResult) {
                $result = $queryResult;
            }
        } else {
            $this->errors['database'] = 'Database connection couldn\'t be established, please try again later!';
        }

        return $result;
    }

    /**
     * Downloads a number of messages from the SOAP server using the peekMessages SOAP method and returns them as an array.
     * @param string $username User's username for logging activity.
     * @param int $numberOfMessages Maximum number of messages to retrieve from the SOAP server.
     * @return array Array of messages from the SOAP server.
     */
    public function downloadMessages(string $username, int $numberOfMessages): array
    {
        $result = [];

        $this->logger->info('SOAP Download Request', [
            'username' => $username,
            'numberOfMessages' => $numberOfMessages
        ]);

        $downloadedMessages = $this->soapWrapper->performSoapFunction($username, 'peekMessages', [
            'username' => $this->soapLogin['username'],
            'password' => $this->soapLogin['password'],
            'count' => $numberOfMessages,
            'deviceMsisdn' => '',
            'countryCode' => '44'
        ]);

        if ($downloadedMessages !== null) {
            $result = $downloadedMessages;
        } else {
            $this->errors['soap'] = 'A SOAP error has occurred, please try again later!';
        }

        return $result;
    }

    /**
     * Gets the latest message's date and time from the database to check for duplicate messages from the SOAP service.
     * @param string $username User's username for logging activity.
     * @return DateTime|null DateTime object of the latest message's date and time, null on failure or no messages stored.
     */
    public function getLatestMessageDateTime(string $username)
    {
        $result = null;

        $this->logger->info('Database Latest Message DateTime Request', ['username' => $username]);

        $query = $this->queries->getLatestMessageDateTime();
        if ($query) {
            $queryResult = $this->dbWrapper->executeAndFetch($query)['received'] ?? '';
            if ($queryResult !== '') {
                try {
                    $result = new DateTime($queryResult);
                } catch (\Exception $e) {
                    $this->logger->error('DateTime Creation Error', ['timeEntered' => $queryResult]);
                }
            }
        } else {
            $this->errors['database'] = 'Database connection couldn\'t be established, please try again later!';
        }

        return $result;
    }

    /**
     * Inserts a message into the database.
     * @param string $username User's username for logging activity.
     * @param array $parsedMessage Message details as a key/value array for database entry.
     * @return bool Whether the insertion was successful.
     */
    public function insertMessage(string $username, array $parsedMessage)
    {
        $result = false;

        $this->logger->info('Database Inserting Message', ['username' => $username, 'message' => $parsedMessage]);

        $query = $this->queries->insertMessage($parsedMessage);
        if ($query) {
            $queryResult = $this->dbWrapper->execute($query);
            if ($queryResult !== null) {
                $result = true;
            }
        } else {
            $this->errors['database'] = 'Database connection couldn\'t be established, please try again later!';
        }

        return $result;
    }

    /**
     * Retrieves all messages from the database.
     * @return array All messages from the database or an empty array on failure.
     */
    public function getAllMessages()
    {
        $result = [];

        $this->logger->info('All Message Data Requested', ['username' => 'admin']);

        $query = $this->queries->getAllMessages();
        if ($query) {
            $queryResult = $this->dbWrapper->executeAndFetchAll($query);
            if ($queryResult) {
                $result = $queryResult;
            }
        } else {
            $this->errors['database'] = 'Database connection couldn\'t be established, please try again later!';
        }

        return $result;
    }

}